### ISSUE TITLE
Add an option to work without Celery?

### ISSUE THREAD

**Issue by philgyford** [beatonma/django-wm#17]
I want to add webmentions to my own website and I really like the look of django-wm – there are so many nice and useful touches. But I don't currently use Celery on it and I'm unlikely to get it set up just to enable webmentions.

Would you be open to me adding an option to work without Celery? e.g. Add two custom management commands to process any outstanding incoming and outgoing webmentions, which could then be run using cron or similar.

I haven't thought in further detail what would be involved in making this work – maybe it would require either adding extra field(s) to the models to indicate whether they were waiting to be processed, or adding another model to store this queue... 

Anyway, if you're open to the idea I'd be happy to give it a go, and if you have any better ideas about how to approach it, that would be appreciated.

**Comment by beatonma** [comment]
Hey, sorry for the late response. Good idea! You are absolutely welcome to work on this and I'd be happy to accept any pull requests that make it more useful/usable.

I started thinking about how I would approach this yesterday and ended up just starting it - https://github.com/beatonma/django-wm/compare/without-celery - basically using the approach you suggested.

The commit is messy but basically:
- Added `settings.WEBMENTIONS_USE_CELERY`
- Bypass any existing `celery` imports if it is not installed.
- Added `PendingIncomingWebmention` and `PendingOutgoingContent` models.
- Added `pending_mentions` management command to process any instances of those models.
- Replaced celery `<function>.delay()` calls with `handle_incoming_webmention` and `handle_outgoing_webmention` (See [here](https://github.com/beatonma/django-wm/compare/without-celery#diff-45d4c766fc447766bf37daf4373ec4349e42e75243e522baa33bb2f00212e7fa)) which handle passing to celery or creating `Pending...` model instances.

I ran out of time so this is completely untested and needs some tidying up but it should be close to working..? Feel free to use this as a starting point if there is anything else you want to add or fix.

**Comment by philgyford** [comment]
Oh this looks great, thank you! Probably nicer than whatever I'd have attempted. I'll try and give it a whirl in the next few days and see if I can think of anything else to do with it. Thanks again.

**Comment by philgyford** [comment]
Sorry I didn't get a chance to look at this sooner - Christmas, New Year, etc got in the way.

I've only had a quick go so far, but some initial questions:

1. Is there a reason why the app doesn't have any migrations? I know I'd have to create a migration for my own app after adding `MentionableMixin` to a model, but it seems very unusual for there to be no migrations for the non-mixin models.
2. There's a typo in `tasks/scheduling.py` on line 14 - it should be `WEBMENTIONS_USE_CELERY` not `WEBMENTION_USE_CELERY` (no `S`).
3. It would be useful to have Admin classes for `PendingIncomingWebmention` and `PendingOutgoingContent` so it's possible to see what's waiting to be dealt with. Otherwise it's hard to know if things are working.
4. I don't think there's anything that prevents duplicate mentions being sent. This can happen (a) if a text links to the same URL more than once, or (b) if an object is saved more than once. I guess this should happen in `tasks.outgoing_webmentions.process_outgoing_webmentions()`?

**Comment by beatonma** [comment]
No problem, same deal with festivities here.

1: Not really. At the time of original release I had seen discussion on whether migrations should be included in git and decided it made sense for the consumer to make their own migrations. I have since learnt the error of my ways. Adding them now may complicate things for any existing users but it's probably the right thing to do overall.

2, 3, 4a: Thanks, will fix.

4b: This was intentional so that the mentioned site can know that the source content has changed for moderation purposes. Of course there's nothing stopping you from changing the content quietly anyway, but that's the intent for allowing duplicates. That said, it may be good to add some sort of checks on incoming mentions.

I'm going to work on this a bit this week. I'm also planning to create a testing tool on my main site - I took down the django-wm.dev testing site a while ago as it wasn't being used much, but it would be handy to have that functionality available again.

**Comment by philgyford** [comment]
Brilliant, thanks! I was hoping to have some time to make the obvious fixes (2, 3) myself but work got in the way. I also haven't worked out how best to use a fork of a third-party app within the local dev version of my site, so it's easier to make changes for a PR.

Yes, you're right about 4b, despite having worked through the Webmention spec some time ago I forgot that it's good to send again in case anything changes. But then, as you say, the onus is on the incoming side to handle any duplicate/updated webmentions appropriately.

**Comment by beatonma** [comment]
[2.1.0](https://pypi.org/project/django-wm/) is now available and the testing tool is now [up and running](https://beatonma.org/webmentions_tester/). Updated setup instructions (without celery) start [here](https://github.com/beatonma/django-wm/blob/master/docs/getting_started_without_celery.md). Let me know how you get on :)
