### ISSUE TITLE
Expand the allowed versions of the required requests package?

### ISSUE THREAD

**Issue by philgyford** [beatonma/django-wm#26]
I've just tried to install django-wm but hit an issue where its specified version of `requests` is older than that allowed by other packages I'm already using.

`setup.cfg` specifies `requests ~= 2.20.0`, so anything like `2.20.*`. But [requests](https://pypi.org/project/requests/) is now up to 2.27.1.

Other things I'm using in this project, as examples, have `>=2.2.1` (flickrapi), `>=2.1.0` (twython), `>=2.0,<3.0` (responses).

Any chance it could be given a more lenient requirement?

(Sorry, after coming here ages ago to ask about a non-celery version of django-wm, I disappeared and only now have I found time to get to grips with it again... and here I am causing trouble once more! These kinds of interrelated dependencies can be such a pain and I only assume I haven't hit a similar problem with my own packages because nobody uses them :) Thanks for your time.)

**Comment by beatonma** [comment]
2.2.0 is now [available](https://pypi.org/project/django-wm/). It should now accept `>=2.20,<3.0`. Likewise for beautifulsoup and the others.

No problem! Likewise - I hadn't touched this project in a long time and wasn't aware of anyone using it. Having some users who are interested in making it better is a good problem to have :)

**Comment by philgyford** [comment]
Thank you so much, very speedy! I've successfully added it locally, and look forward to trying to get it all working again!
