### ISSUE TITLE
Single incoming webmention repeatedly being processed.

### ISSUE THREAD

**Issue by garrettc** [beatonma/django-wm#43]
Hi,

I'm seeing a bug where a webmention is being continuously processed and keeps adding entries to the Webmentions page in admin (my cron job runs at 45 minutes past every hour).

<img width="1167" alt="Screenshot 2022-10-24 at 09 06 21" src="https://user-images.githubusercontent.com/25522/197490030-9c63275f-e142-4b4b-9008-0f2177d155da.png">

Each entry has the note: 

`Unable to find matching page on our server for url 'https://polytechnic.co.uk/blog/2022/03/site-update/'`

Which is a separate issue at my end in trying to get django-wm to play with Wagtail, I have other incoming webmentions that fail to find the post, but aren't repeating like this. 

There's nothing outstanding in the "Pending incoming webmentions" screen.

I've spoken with @philgyford (the source of the webmention) and he doesn't see anything strange at his end.

Any ideas on how to diagnose this? Happy to give you a database snapshot if needed.

python 3.7.3
Django 3.2.14
django-wm 3.1.0

**Comment by philgyford** [comment]
Fwiw, these are the only references to that post in my Outgoing Webmentions.

![209CA1A0-4272-444E-9DD9-79D1B93CDBAD](https://user-images.githubusercontent.com/66670/197523107-f88fb647-0812-486e-8498-9b52b0cfb86b.jpeg)

I have no Pending Outgoing Contents.

**Comment by beatonma** [comment]
Curious - I'm getting something very similar.

![Screenshot from 2022-10-24 18-23-16](https://user-images.githubusercontent.com/12682046/197587914-01708c21-cbb4-46cd-af92-29657556ae08.png)

Thank you both - I'll look into it and get back to you asap!

**Comment by beatonma** [comment]
`3.1.1` is now available and should fix this.

There was a bug when retrying a failed webmention. One instance of `OutgoingWebmentionStatus` could trigger a retry, but a different instance could be used to track the progress of that retry. The trigger was never updated with the results so it triggered again the next time.

@philgyford please let me know once you get a chance to update so we can verify that this was the cause.

They should retry once more, and potentially a few more times (depending on `settings.WEBMENTIONS_MAX_RETRIES`, default 5) if there are network errors.

Thanks again and sorry for the inconvenience.

**Comment by philgyford** [comment]
Hi - my site's updated to 3.1.1 now.

**Comment by beatonma** [comment]
Great, thanks - looks good from here!

@garrettc are you still receiving duplicates?

**Comment by garrettc** [comment]
Looks good here. I haven’t received any duplicates since 2:45pm 👍
