### ISSUE TITLE
`allow_outgoing_webmentions` field does not display on custom forms

### ISSUE THREAD

**Issue by campegg** [beatonma/django-wm#47]
I am using custom forms on my site, but after upgrading from v3.1.0 to v4.0.0, the `allow_outgoing_webmentions` checkbox does not display. The form views look like this:

```
class AdminNoteCreate(LoginRequiredMixin, CreateView):
    model = Note
    template_name = "note.html"
    fields = [
        "text",
        "in_reply_to",
        "create_date",
        "rss_only",
        "allow_outgoing_webmentions",
    ]
```

And the template looks like this:

```
<h4>Note Meta</h4>
<div>
    {{ form.allow_outgoing_webmentions }}
    <label for="{{ form.allow_outgoing_webmentions.id_for_label }}">Send webmentions</label>
</div>
<div>
    {{ form.rss_only }}
    <label for="{{ form.rss_only.id_for_label }}">RSS only</label>
</div>
```

This is what I see:

<img width="176" alt="allow_outgoing_webmentions" src="https://user-images.githubusercontent.com/2051083/204167378-7be6ccb0-1671-45a8-817b-7551c68ddfad.png">

**Comment by beatonma** [comment]
I'm afraid I haven't been able to reproduce this yet - [this](https://github.com/beatonma/django-wm/blob/4.0.1/sample-project/issues_app/views.py) renders fine for me.

4.0.0 changed the default value of `allow_outgoing_webmentions` to make it configurable - can you confirm that you ran `makemigrations` and `migrate` after upgrading? I've just tried doing this and it rendered fine with or without running migrations but it's the only relevant thing I can think of that changed.

Can you view source in your browser and confirm that the checkbox isn't somehow hidden by css?

I'm all out of ideas after that but I'd at least like to cross those off the list.

Thanks!

**Comment by campegg** [comment]
Thanks for taking a look! I have run `makemigrations` and `migrate`. This is what I see when I view source; the checkbox is definitely not there:

<img width="439" alt="wm_view_source" src="https://user-images.githubusercontent.com/2051083/205142507-3c731e64-151b-405b-8c51-b971e952c7d6.png">

Since it was the only other change I made, I also tried setting the value of `WEBMENTIONS_ALLOW_OUTGOING_DEFAULT` in my settings file to both `True` and `False`, as well as removing it completely, but that didn't have any effect (not that I really expected it to).

**Comment by beatonma** [comment]
Good to rule those out, thanks. I'll dig around some more...

**Comment by beatonma** [comment]
- It doesn't seem to be affected by translation or localisation settings.
- Misconfiguring the field names in the CreateView raises a FieldError, so it's not that.

The only way I've found for the checkbox not to render is if the field is misspelled in the template (e.g. `{{ form.misspelled__allow_outgoing_webmentions }}`).

That doesn't appear to be the case for you, and I don't see why it would have been affected by the update, but can you please try adding `{{ form }}` to your template to see what that renders?

**Comment by campegg** [comment]
That works! (At least, the checkbox renders.)

<img width="1506" alt="django-wm-test-form" src="https://user-images.githubusercontent.com/2051083/205373791-f1909276-8a1e-4bfd-8fd1-660812e584e2.png">

**Comment by campegg** [comment]
OK, so I deleted the local dev version of my site, set up a new virtual environment, re-cloned my site repo and tried again. And guess what? It worked. So I did the same on my live site and it worked there, too. I'm guessing it was a problem on my part, not an issue with the package. Sorry for the runaround!

**Comment by beatonma** [comment]
Weird! No problem, glad you got it sorted out.

Aside/TIL: The hidden `initial-` field is used to check whether a field has changed when submitting a form - [it's a core Django thing](https://github.com/django/django/blob/main/django/forms/forms.py#L212).
