### ISSUE TITLE
Small error in QuotableAdmin's search_fields

### ISSUE THREAD

**Issue by philgyford** [beatonma/django-wm#50]
I've taken to running [some tests](https://adamj.eu/tech/2023/03/17/django-parameterized-tests-model-admin-classes/) across my projects' Admin classes and came across this errors in django-wm's:

- In [`QuotableAdmin`](https://github.com/beatonma/django-wm/blob/main/mentions/admin.py#L35) it lists `"hcard"` in `search_fields` – but that's a ForeignKey and can't be searched on. Maybe it should be `"hcard__name"`?

**Comment by beatonma** [comment]
Good catch - thanks once again!
