### ISSUE TITLE
Clean Install Breaks Incoming Webmentions

### ISSUE THREAD

**Issue by campegg** [beatonma/django-wm#53]
From v2.0.0 onwards, mf2py supports img alt text by default, which breaks incoming webmentions, since (I think!) the line [`hcard.avatar = urljoin(source_url, hcard.avatar)`](https://github.com/beatonma/django-wm/blob/02d75fd66cc6372fb4520ad228ec107cec1055ae/mentions/tasks/incoming/remote.py#L100C9-L100C14) in `mentions/tasks/incoming/remote.py` expects `source_url` to be a string, but is being passed an object with value and alt instead of just the URL string. Trying to parse incoming webmentions throws `TypeError: Cannot mix str and non-str arguments` (see stack trace below).

The current requirements (`mf2py>=1.1.2`) will mean a clean install of django-wm will default to the latest version (currently 2.0.1). Downgrading to version 1.1.3 does solve the problem, however.

[stack_trace.md](https://github.com/beatonma/django-wm/files/14104267/stack_trace.md)

**Comment by beatonma** [comment]
Thank you - fix available in release [4.0.4](https://pypi.org/project/django-wm/4.0.4/).

**Comment by campegg** [comment]
Thank you, @beatonma—really appreciate the quick fix!

**Comment by beatonma** [comment]
(Not that quick - I came across and fixed tthis ~6 weeks ago while adding something for the next release but neglected to publish it :$)
