### ISSUE TITLE
ProgrammingError: relation "mentions_hcard" does not exist

### ISSUE THREAD

**Issue by rasulkireev** [beatonma/django-wm#6]
Michael,

I hope I am not becoming an annoying who asks you for any error I receive. No rush on this, but it would be cool if you could look at it. Meanwhile, I will try to figure this out be looking into your codebase.

Here is the full traceback.

![Screen Shot 2019-12-22 at 17 02 10](https://user-images.githubusercontent.com/8257474/71327939-2c6dff00-24dd-11ea-8852-0d4322419b20.png)

**Comment by beatonma** [comment]
Hey, sorry for the late response.

That looks like a database migration issue. Did you run `python manage.py makemigrations` and `python manage.py migrate` after installing `mentions`?

Sometimes it helps to include the name of your Django app in those commands, like `python manage.py makemigrations my_app` and `python manage.py migrate my_app`.

If you are able to look at your database structure there should be tables called `mentions_hcard`, `mentions_simplemention` and `mentions_webmention` which are created when you run the migrations.

Questions are good! It helps to know about any issues people have so I can make improvements in implementation/documentation/whatever and make the library as simple as possible to use. Let me know how you get on :)

Michael
